# Generated by Django 4.2.22 on 2025-06-07 09:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Film',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_number', models.CharField(blank=True, max_length=50)),
                ('original_title', models.CharField(max_length=255)),
                ('english_title', models.CharField(blank=True, max_length=255)),
                ('original_subtitle', models.CharField(blank=True, max_length=255)),
                ('english_subtitle', models.CharField(blank=True, max_length=255)),
                ('production_year', models.IntegerField()),
                ('director', models.CharField(max_length=255)),
                ('producer', models.CharField(blank=True, max_length=255)),
                ('co_producer', models.CharField(blank=True, max_length=255)),
                ('instructor_supervisor', models.CharField(blank=True, max_length=255)),
                ('movie_language', models.CharField(max_length=100)),
                ('subtitle_languages', models.CharField(blank=True, max_length=255)),
                ('working_title', models.CharField(blank=True, max_length=255)),
                ('complementary_data', models.TextField(blank=True)),
                ('genre', models.CharField(choices=[('drama', 'Drama'), ('documentary', 'Documentary'), ('comedy', 'Comedy'), ('tragedy', 'Tragedy'), ('other', 'Other')], max_length=20)),
                ('genre_other', models.CharField(blank=True, max_length=100)),
                ('project_type', models.CharField(choices=[('short_film', 'Short Film'), ('animation', 'Animation'), ('tv_program', 'TV Program'), ('newsreel', 'Newsreel'), ('advertising', 'Advertising'), ('other', 'Other')], max_length=20)),
                ('project_type_other', models.CharField(blank=True, max_length=100)),
                ('main_cast', models.TextField(blank=True)),
                ('persons_shown', models.TextField(blank=True)),
                ('persons_speaking', models.TextField(blank=True)),
                ('persons_spoken_about', models.TextField(blank=True)),
                ('additional_info', models.TextField(blank=True)),
                ('doi', models.CharField(blank=True, max_length=255)),
                ('streaming_link', models.URLField(blank=True)),
                ('additional_webpage', models.URLField(blank=True)),
                ('archive_notes', models.TextField(blank=True)),
                ('production_country', models.CharField(blank=True, max_length=100)),
                ('production_date', models.DateField(blank=True, null=True)),
                ('production_company', models.CharField(blank=True, max_length=255)),
                ('cooperation_partners', models.TextField(blank=True)),
                ('supported_by', models.TextField(blank=True)),
                ('inside_locations', models.TextField(blank=True)),
                ('outside_locations', models.TextField(blank=True)),
                ('number_of_episodes', models.IntegerField(blank=True, null=True)),
                ('color', models.CharField(choices=[('black_white', 'Black and White'), ('color', 'Color'), ('other', 'Other')], max_length=20)),
                ('general_type', models.CharField(choices=[('film', 'Film'), ('digital_video', 'Digitally on Video'), ('digital_ramdisk', 'Digitally on Ramdisk'), ('other', 'Other')], max_length=20)),
                ('film_format', models.CharField(blank=True, choices=[('8mm', '8mm'), ('other', 'Other')], max_length=20)),
                ('digital_format', models.CharField(blank=True, choices=[('digibeta', 'Digibeta'), ('dv', 'DV'), ('mini_dv', 'Mini DV'), ('dvcam', 'DVCAM'), ('dvcpro', 'DVCPRO'), ('hdcam', 'HDCAM'), ('digital_8', 'Digital 8 (8mm)'), ('other', 'Other')], max_length=20)),
                ('screen_ratio', models.CharField(blank=True, choices=[('4:3', '4:3'), ('16:9', '16:9'), ('16:10', '16:10'), ('21:9', '21:9'), ('other', 'Other')], max_length=10)),
                ('sound_format', models.CharField(blank=True, choices=[('mono', 'Mono'), ('stereo', 'Stereo'), ('dolby_5_1', 'Dolby 5.1 Surround'), ('other', 'Other')], max_length=20)),
                ('running_time', models.CharField(blank=True, max_length=10)),
                ('brief_introduction_en', models.TextField()),
                ('brief_introduction_local', models.TextField(blank=True)),
                ('logline', models.TextField(blank=True)),
                ('synopsis_en', models.TextField()),
                ('synopsis_local', models.TextField(blank=True)),
                ('content_summary_en', models.TextField()),
                ('content_summary_local', models.TextField(blank=True)),
                ('keywords', models.TextField()),
                ('time_of_movie', models.CharField(blank=True, max_length=255)),
                ('target_audience', models.CharField(max_length=255)),
                ('copyright_owners', models.TextField(blank=True)),
                ('access_levels', models.CharField(blank=True, max_length=255)),
                ('trailer', models.FileField(blank=True, upload_to='trailers/')),
                ('poster', models.ImageField(blank=True, upload_to='posters/')),
                ('logo', models.ImageField(blank=True, upload_to='logos/')),
                ('distributor', models.CharField(blank=True, max_length=255)),
                ('final_credits', models.CharField(blank=True, max_length=255)),
                ('premiere_info', models.TextField(blank=True)),
                ('festival_participation', models.TextField(blank=True)),
                ('festival_prizes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_films', to=settings.AUTH_USER_MODEL)),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='films.institution')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['original_title'], name='films_film_origina_105a18_idx'), models.Index(fields=['production_year'], name='films_film_product_aac8ad_idx'), models.Index(fields=['genre'], name='films_film_genre_00aeeb_idx'), models.Index(fields=['project_type'], name='films_film_project_47717e_idx')],
            },
        ),
    ]
